#!/usr/bin/env node

const { Command } = require("commander")
const { buildController } = require("./cli/build")
const program = new Command()

program.name("ebp-cli").description("CLI Commands for Express Boilerplate").version("0.0.1")

program
    .command("build:controller")
    .description("Build Controller, Usage: node ebp build:controller <controller-name>")
    .argument("<controllerName>", "Controller Name")
    .action(async (controllerName) => {
        console.log(`Building Controller: ${controllerName}`)
        await buildController(controllerName)
    })

program.parse(process.argv)
