#!/usr/bin/env node

const { Command } = require("commander")
const { init } = require("./system/cli")
const program = new Command()

program.name("ebp").description("CLI Commands for Express Boilerplate").version("0.0.1")

init(program)

/**
 * * add your commands here
 * * use commander to add commands, https://www.npmjs.com/package/commander
 * 
 * 
 * 
 **/

program.parse(process.argv)
