#!/usr/bin/env node

const { Command } = require("commander")
const { init } = require("./system/cli")
const program = new Command()

program.name("ebp").description("CLI Commands for Express Boilerplate").version("0.0.1")

init(program)

program.parse(process.argv)
