site_name: Express JS Api Boilerplate
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Directory Structure: directory-structure.md
  - Available Scripts: available-scripts.md
  - Deployment: deployment.md
  - Resources: resources.md
theme:
  name: material
  highlightjs: true