site_name: Express JS Api Boilerplate
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Directory Structure: directory_structure.md
  - Available Scripts: available_scripts.md
  - Deployment: deployment.md
  - Resources: resources.md
theme:
  name: material
  highlightjs: true