site_name: 3rd planet | framework x Documentation
repo_url: https://github.com/3rd-planet/framework-x.git
site_url: https://create-express-boilerplate.com
site_author: msamgan
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Directory Structure: directory-structure.md
    - Available Scripts: available-scripts.md
    - Commands: commands.md
    - Deployment: deployment.md
    - Contributors: contributors.md
theme:
    name: material
    highlightjs: true
